{"name": "test_login_with_invalid_credentials", "status": "passed", "start": 1716809471645, "stop": 1716809477449, "uuid": "852c02b3-a826-4aa6-911c-b888fedb72a5", "historyId": "ad68f1bbe0a2e168898b446d810cdfd0", "testCaseId": "ad68f1bbe0a2e168898b446d810cdfd0", "fullName": "tests.test_login_002.TestLogin_002#test_login_with_invalid_credentials", "labels": [{"name": "tag", "value": "sanity_test"}, {"name": "tag", "value": "@pytest.mark.usefixtures('setup_teardown')"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login_002"}, {"name": "subSuite", "value": "TestLogin_002"}, {"name": "host", "value": "DESKTOP-5K904R3"}, {"name": "thread", "value": "17228-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login_002"}]}