{"name": "test_login_with_invalid_credentials", "status": "passed", "attachments": [{"name": "log", "source": "1a7ccea6-3295-466d-b829-24fe60c59a18-attachment.txt", "type": "text/plain"}], "start": 1718351402141, "stop": 1718351408956, "uuid": "d4e03a56-d0a7-4d37-a1d8-3c51bc68c11c", "historyId": "ad68f1bbe0a2e168898b446d810cdfd0", "testCaseId": "ad68f1bbe0a2e168898b446d810cdfd0", "fullName": "tests.test_login_002.TestLogin_002#test_login_with_invalid_credentials", "labels": [{"name": "tag", "value": "sanity_test"}, {"name": "tag", "value": "@pytest.mark.usefixtures('setup_teardown')"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login_002"}, {"name": "subSuite", "value": "TestLogin_002"}, {"name": "host", "value": "DESKTOP-5K904R3"}, {"name": "thread", "value": "38724-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login_002"}]}